Name: CVE-2011-4138
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-4138
Phase: Assigned (20111019)
Category: 
Reference: MLIST:[oss-security] 20110911 CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws
Reference: URL:http://openwall.com/lists/oss-security/2011/09/11/1
Reference: MLIST:[oss-security] 20110913 Re: CVE Request -- Django: v1.3.1, v1.2.7 multiple security flaws
Reference: URL:http://openwall.com/lists/oss-security/2011/09/13/2
Reference: CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=737366
Reference: CONFIRM:https://www.djangoproject.com/weblog/2011/sep/09/
Reference: CONFIRM:https://www.djangoproject.com/weblog/2011/sep/10/127/
Reference: DEBIAN:DSA-2332
Reference: URL:http://www.debian.org/security/2011/dsa-2332
Reference: SUSE:openSUSE-SU-2012:0653
Reference: URL:https://hermes.opensuse.org/messages/14700881
Reference: SECUNIA:46614
Reference: URL:http://secunia.com/advisories/46614

The verify_exists functionality in the URLField implementation in
Django before 1.2.7 and 1.3.x before 1.3.1 originally tests a URL's
validity through a HEAD request, but then uses a GET request for the
new target URL in the case of a redirect, which might allow remote
attackers to trigger arbitrary GET requests with an unintended source
IP address via a crafted Location header.


Current Votes:
None (candidate not yet proposed)


