Name: CVE-2017-7233
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2017-7233
Phase: Assigned (20170322)
Category: 
Reference: CONFIRM:https://www.djangoproject.com/weblog/2017/apr/04/security-releases/
Reference: DEBIAN:DSA-3835
Reference: URL:http://www.debian.org/security/2017/dsa-3835
Reference: REDHAT:RHSA-2017:3093
Reference: URL:https://access.redhat.com/errata/RHSA-2017:3093
Reference: REDHAT:RHSA-2017:1445
Reference: URL:https://access.redhat.com/errata/RHSA-2017:1445
Reference: REDHAT:RHSA-2017:1451
Reference: URL:https://access.redhat.com/errata/RHSA-2017:1451
Reference: REDHAT:RHSA-2017:1462
Reference: URL:https://access.redhat.com/errata/RHSA-2017:1462
Reference: REDHAT:RHSA-2017:1470
Reference: URL:https://access.redhat.com/errata/RHSA-2017:1470
Reference: REDHAT:RHSA-2017:1596
Reference: URL:https://access.redhat.com/errata/RHSA-2017:1596
Reference: BID:97406
Reference: URL:http://www.securityfocus.com/bid/97406
Reference: SECTRACK:1038177
Reference: URL:http://www.securitytracker.com/id/1038177

Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18
relies on user input in some cases to redirect the user to an "on
success" URL. The security check for these redirects (namely
``django.utils.http.is_safe_url()``) considered some numeric URLs
"safe" when they shouldn't be, aka an open redirect vulnerability.
Also, if a developer relies on ``is_safe_url()`` to provide safe
redirect targets and puts such a URL into a link, they could suffer
from an XSS attack.


Current Votes:
None (candidate not yet proposed)


