Name: CVE-2009-5011
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2009-5011
Phase: Assigned (20101019)
Category: 
Reference: CONFIRM:http://code.google.com/p/pyftpdlib/issues/detail?id=100
Reference: CONFIRM:http://code.google.com/p/pyftpdlib/source/browse/trunk/HISTORY
Reference: CONFIRM:http://code.google.com/p/pyftpdlib/source/detail?r=543
Reference: CONFIRM:http://code.google.com/p/pyftpdlib/source/diff?spec=svn543&r=543&format=side&path=/trunk/pyftpdlib/ftpserver.py

Race condition in the FTPHandler class in ftpserver.py in pyftpdlib
before 0.5.2 allows remote attackers to cause a denial of service
(daemon outage) by establishing and then immediately closing a TCP
connection, leading to the getpeername function having an ENOTCONN
error, a different vulnerability than CVE-2010-3494.


Current Votes:
None (candidate not yet proposed)


