Name: CVE-2016-4989
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-4989
Phase: Assigned (20160524)
Category: 
Reference: MLIST:[oss-security] 20160621 SELinux troubles
Reference: URL:http://seclists.org/oss-sec/2016/q2/574
Reference: CONFIRM:https://bugzilla.redhat.com/show_bug.cgi?id=1346461
Reference: CONFIRM:https://github.com/fedora-selinux/setroubleshoot/commit/dda55aa50db95a25f0d919c3a0d5871827cdc40f
Reference: CONFIRM:https://github.com/fedora-selinux/setroubleshoot/commit/e69378d7e82a503534d29c5939fa219341e8f2ad
Reference: REDHAT:RHSA-2016:1267
Reference: URL:https://rhn.redhat.com/errata/RHSA-2016-1267.html
Reference: REDHAT:RHSA-2016:1293
Reference: URL:https://access.redhat.com/errata/RHSA-2016:1293
Reference: SECTRACK:1036144
Reference: URL:http://securitytracker.com/id/1036144

setroubleshoot allows local users to bypass an intended container
protection mechanism and execute arbitrary commands by (1) triggering
an SELinux denial with a crafted file name, which is handled by the
_set_tpath function in audit_data.py or via a crafted (2) local_id or
(3) analysis_id field in a crafted XML document to the run_fix
function in SetroubleshootFixit.py, related to the
subprocess.check_output and commands.getstatusoutput functions, a
different vulnerability than CVE-2016-4445.


Current Votes:
None (candidate not yet proposed)


