Name: CVE-2016-10149
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2016-10149
Phase: Assigned (20170119)
Category: 
Reference: MLIST:[oss-security] 20170119 Re: CVE request: python-pysaml2 XML external entity attack
Reference: URL:http://www.openwall.com/lists/oss-security/2017/01/19/5
Reference: MISC:https://github.com/rohe/pysaml2/issues/366
Reference: CONFIRM:https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850716
Reference: CONFIRM:https://github.com/rohe/pysaml2/commit/6e09a25d9b4b7aa7a506853210a9a14100b8bc9b
Reference: CONFIRM:https://github.com/rohe/pysaml2/pull/379
Reference: DEBIAN:DSA-3759
Reference: URL:http://www.debian.org/security/2017/dsa-3759
Reference: REDHAT:RHSA-2017:0936
Reference: URL:https://access.redhat.com/errata/RHSA-2017:0936
Reference: REDHAT:RHSA-2017:0937
Reference: URL:https://access.redhat.com/errata/RHSA-2017:0937
Reference: REDHAT:RHSA-2017:0938
Reference: URL:https://access.redhat.com/errata/RHSA-2017:0938
Reference: BID:97692
Reference: URL:http://www.securityfocus.com/bid/97692

XML External Entity (XXE) vulnerability in PySAML2 4.4.0 and earlier
allows remote attackers to read arbitrary files via a crafted SAML XML
request or response.


Current Votes:
None (candidate not yet proposed)


