Name: CVE-2012-2135
Status: Candidate
URL: http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-2135
Phase: Assigned (20120404)
Category: 
Reference: MLIST:[oss-security] 20120425 CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated
Reference: URL:http://www.openwall.com/lists/oss-security/2012/04/25/2
Reference: MLIST:[oss-security] 20120425 Re: CVE Request: Python 3.2/3.3 utf-16 decoder unicode_decode_call_errorhandler aligned_end is not updated
Reference: URL:http://www.openwall.com/lists/oss-security/2012/04/25/4
Reference: MISC:http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=670389
Reference: MISC:http://bugs.python.org/issue14579
Reference: UBUNTU:USN-1615-1
Reference: URL:http://www.ubuntu.com/usn/USN-1615-1
Reference: UBUNTU:USN-1616-1
Reference: URL:http://www.ubuntu.com/usn/USN-1616-1
Reference: SECUNIA:51089
Reference: URL:http://secunia.com/advisories/51089
Reference: SECUNIA:51087
Reference: URL:http://secunia.com/advisories/51087

The utf-16 decoder in Python 3.1 through 3.3 does not update the
aligned_end variable after calling the
unicode_decode_call_errorhandler function, which allows remote
attackers to obtain sensitive information (process memory) or cause a
denial of service (memory corruption and crash) via unspecified
vectors.


Current Votes:
None (candidate not yet proposed)


